### PR TITLE
Support for reverse patching

### PR DESCRIPTION
**Pull request by graingert**

### CODE REVIEW

**Comment by graingert** [comment]
@cscorley I've opened a bunch of pull requests, but they all sort-of depend on each other.

Merging this one will close all my issues and PRs automatically.

**Comment by graingert** [comment]
@cscorley any movement on this?

**Comment by cscorley** [comment]
@graingert sorry, no. I am rather busy at the moment trying to graduate from my phd program. I'd like to be able to take the time to give this a proper review and don't have anyone I know that could do it for me.

**Comment by graingert** [comment]
@cscorley congratulations on your PHD! any chance of a new release?

**Comment by cscorley** [comment]
Yes, thank you. I realized late last night that I need to resetup the whole
thing on my machine. Will try to get that done after work duties

**Pull request merged**
