### PR TITLE
support of git binary files

### PR DESCRIPTION
**Pull request by ramusus**

### CODE REVIEW

**Comment by cscorley** [comment]
Hey, cool, thanks for this! I'll try to get this merged in (after fixing Travis).

**Comment by cscorley** [comment]
@ramusus Travis should be fixed now if you'd like to rebase this commit onto HEAD. I'll merge if it passes. Thanks!!

**Comment by ramusus** [comment]
Thanks! Travis has passed now!

**Comment by cscorley** [comment]
Thanks again!

**Pull request merged**
